language: php

php:
  - 7.1

env:
  - DB=mysql

dist: trusty
sudo: required

before_script:
  - if [[ "$DB" == "mysql" ]]; then /Applications/MAMP/Library/bin/mysql -u root -p root -e "create database IF NOT EXISTS test_01_01;" fi
